version: '3'
services:
  whatsapp-api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: always 